PTM/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.Mvc;
using PTM.Models;
using System.Threading.Tasks;
using System.Data.Entity;
using PagedList;
using PagedList.Mvc;

namespace PTM.Controllers
{
    public class ProjectController : Controller
    {
        // GET: Project
        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Create()
        {
            CreateProjectModel model=new CreateProjectModel();
            using (PTMContext db = new PTMContext())
            {
                model.CheckedDepartments = await db.Departments.Select(d => new CheckedDepartment { Id = d.Id, Name = d.Name, UsersCount=d.Users.Count, IsChecked = false }).ToListAsync();
                //for (int i = 0; i < model.CheckedDepartments.Count; i++)
                //{
                //    int id = model.CheckedDepartments[i].Id;
                //    model.CheckedDepartments[i].CheckedUsers = await db.UserInfo.Where(u => u.Department.Id == id).Select(u => new CheckedUser { Id = u.Id, Name = u.FullName, IsChecked = false }).ToListAsync();
                //    //   model.CheckedUsers.Add(db.UserInfo.Where(u => u.Department.Id == id).ToList().Select(u => new CheckedUser { Id = u.Id, Name = u.FullName, IsChecked = false }).ToList());
                //}
                //var CheckedUsers=await db.UserInfo.Select(u => new CheckedUser { Id = u.Id, Name = u.FullName, IsChecked = false }).ToListAsync();
            }
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Create(CreateProjectModel model)
        {




            using (PTMContext db = new PTMContext())
            {
                model.CheckedDepartments = await db.Departments.Select(d => new CheckedDepartment { Id = d.Id, Name = d.Name, UsersCount = d.Users.Count, IsChecked = false }).ToListAsync();
                for (int i = 0; i < model.CheckedDepartments.Count; i++)
                {
                    model.CheckedDepartments[i].CheckedUsers = db.UserInfo.Where(u => u.Department.Id == model.CheckedDepartments[i].Id).ToList().Select(u => new CheckedUser { Id = u.Id, Name = u.FullName, IsChecked = false }).ToList();
                    //modelCheckedUsers.Add(db.UserInfo.Where(u => u.Department.Id == model.CheckedDepartments[i].Id).ToList().Select(u => new CheckedUser { Id = u.Id, Name = u.FullName, IsChecked = false }).ToList());
                }
            }
            return View(model);
        }


        [Authorize]
        public async Task<ActionResult> Index()
        {

            ProjectsModel model = new ProjectsModel();
            using (PTMContext db = new PTMContext())
            {

                //db.Departments.Add(new Department { Name = "No Department", DepartmentStatus = DepartmentStatus.Active });
                //db.Projects.Add(new Project { Name = "TestProject_1", ProjectStatus = ProjectStatus.NotStarted });
                //db.Projects.Add(new Project { Name = "TestProject_2", ProjectStatus = ProjectStatus.Completed });
                //db.SaveChanges();
                //List<Project> projects = await db.Projects.ToListAsync();
                //projects[0].Users.Add(db.Users.FirstOrDefault(u => u.UserName == "2"));
                //db.Projects.Add(new Project { Name = "TestProject_3", ProjectStatus = ProjectStatus.Failed });
                //db.Projects.Add(new Project { Name = "TestProject_4", ProjectStatus = ProjectStatus.Active });


                //db.SaveChanges();
                //Project pr = db.Projects.ToList()[1];
                //pr.Departments.Add(db.Departments.ToList()[1]);
                //pr.Users.Add(db.Users.ToList()[1]);
                //db.SaveChanges();
                model.Projects =await db.Projects.Include(p => p.Users).Include(p => p.Departments).ToListAsync();

                //foreach (Department d in model.Departments)
                //{
                //    d.Users = db.Departments.ToList()[0].Users;
                //}
            }
            return View(model);
        }


        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Project(int id)
        {
            ProjectModel model = new ProjectModel();
            using (PTMContext db = new PTMContext())
            {
                var pr = await db.Projects.Include(p => p.Tasks).Include(p=>p.Departments).Include(p=>p.Users).FirstOrDefaultAsync(p => p.Id == id);
                model.Project = pr;
            }
            return View(model);
        }

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> GetTasks(int id)
        {
            List<Models.Task> Tasks=new List<Models.Task>();
            Tasks model=new Tasks();

            using (PTMContext db=new PTMContext())
            {
                var pr = await db.Projects.Include(p=>p.Tasks).FirstOrDefaultAsync(p=>p.Id==id);
                pr.Tasks.Add(new Models.Task {Name="Task1", TaskStatus=Models.TaskStatus.Submitted, IsBug=true });
                pr.Tasks.Add(new Models.Task { Name = "Task2", TaskStatus = Models.TaskStatus.Submitted });
                pr.Tasks.Add(new Models.Task { Name = "Task3", TaskStatus = Models.TaskStatus.Submitted });
                pr.Tasks.Add(new Models.Task { Name = "Task4", TaskStatus = Models.TaskStatus.QA });
                Tasks = pr.Tasks.ToList();
            }
            model.Submitted = Tasks.Where(t => t.TaskStatus == Models.TaskStatus.Submitted).ToList();
            model.InProgress = Tasks.Where(t => t.TaskStatus == Models.TaskStatus.InProgress).ToList();
            model.QA = Tasks.Where(t => t.TaskStatus == Models.TaskStatus.QA).ToList();
            model.Repeated = Tasks.Where(t => t.TaskStatus == Models.TaskStatus.Repeated).ToList();
            model.Discussed = Tasks.Where(t => t.TaskStatus == Models.TaskStatus.Discussed).ToList();
            model.Completed = Tasks.Where(t => t.TaskStatus == Models.TaskStatus.Completed).ToList();
            return PartialView(model);
        }
    }
}

PTM/Controllers/WorkerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.Mvc;
using PTM.Models;
using System.Threading.Tasks;
using System.Data.Entity;
using Newtonsoft.Json;
using PTM.Models.WorkerModels;
using PagedList;
using PagedList.Mvc;

namespace PTM.Controllers
{
    public class WorkerController : Controller
    {
        //[HttpGet]
        //[Authorize]
        //public async Task<ActionResult> Index()
        //{
        //    List<UserInfo> query;
        //    using (PTMContext db = new PTMContext())
        //    {
        //        query = await db.UserInfo.Include(u => u.Projects).Include(u=>u.Department).ToListAsync();
        //    }
        //    List<WorkersModel> resQuery = query.Select(u => new WorkersModel { N = query.IndexOf(u)+1, Name = u.FullName, Department =(u.Department!=null)?u.Department.Name:"", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).OrderBy(u=>u.N).ToList();
        //    return View(resQuery.ToPagedList(1, 20));
        //}

        //[HttpGet]
        //[Authorize]
        //public async Task<ActionResult> GetWorkers(string sortOrder, string q, int page = 1, int pageSize = 20)
        //{
        //    q = String.IsNullOrEmpty(q) ? "" : q;
        //    ViewBag.CurrentFilter = q;

        //    page = page > 0 ? page : 1;
        //    pageSize = pageSize > 0 ? pageSize : 20;

        //    ViewBag.CurrentPageSize = pageSize;
        //    ViewBag.CurrentSort = sortOrder;

        //    List<UserInfo> query;
        //    using (PTMContext db = new PTMContext())
        //    {
        //        query = await db.UserInfo.Include(u => u.Projects).OrderBy(u => u.FullName).Include(u => u.Department).Where(u => u.FullName.Contains(q)).ToListAsync();
        //    }
        //    List<WorkersModel> resQuery;

        //    switch (sortOrder)
        //    {
        //        case "n":
        //            resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderBy(u => u.Id).ToList();
        //            break;
        //        case "name":
        //            resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderBy(u => u.Name).ToList();
        //            break;
        //        case "department":
        //            resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderBy(u => u.Department).ToList();
        //            break;
        //        case "project":
        //            resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderBy(u => u.ProjectsCount).ToList();
        //            break;
        //        case "status":
        //            resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderBy(u => u.UserStatus).ToList();
        //            break;


        //        case "n_desc":
        //            resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderByDescending(u => u.Id).ToList();
        //            break;
        //        case "name_desc":
        //            resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderByDescending(u => u.Name).ToList();
        //            break;
        //        case "department_desc":
        //            resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderByDescending(u => u.Department).ToList();
        //            break;
        //        case "project_desc":
        //            resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderByDescending(u => u.ProjectsCount).ToList();
        //            break;
        //        case "status_desc":
        //            resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderByDescending(u => u.UserStatus).ToList();
        //            break;

        //        default:
        //            resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderBy(u => u.Id).ToList();
        //            break;

        //    }




        //    return PartialView(resQuery.ToPagedList(page, pageSize));
        //}

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Index(string sortOrder, string q, int page = 1, int pageSize = 20)
        {
            q = String.IsNullOrEmpty(q) ? "" : q;
            ViewBag.CurrentFilter =  q;

            page = page > 0 ? page : 1;
            pageSize = pageSize > 0 ? pageSize : 20;

            ViewBag.CurrentPageSize = pageSize;
            ViewBag.CurrentSort = sortOrder;

            List<UserInfo> query;
            using (PTMContext db = new PTMContext())
            {
                query = await db.UserInfo.Include(u => u.Projects).OrderBy(u => u.FullName).Include(u=>u.Department).Where(u=>u.FullName.Contains(q)).ToListAsync();
            }
            List<WorkersModel> resQuery;
               
                switch (sortOrder)
                {
                case "n":
                    resQuery = query.Select(u => new WorkersModel { Id=u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u=>u.Name.Contains(q)).OrderBy(u => u.Id).ToList();
                    break;
                case "name":
                        resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderBy(u=>u.Name).ToList();
                    break;
                case "department":
                    resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderBy(u => u.Department).ToList();
                    break;
                case "project":
                    resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderBy(u => u.ProjectsCount).ToList();
                    break;
                case "status":
                    resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderBy(u => u.UserStatus).ToList();
                    break;


                case "n_desc":
                    resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderByDescending(u => u.Id).ToList();
                    break;
                case "name_desc":
                    resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderByDescending(u => u.Name).ToList();
                    break;
                case "department_desc":
                    resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderByDescending(u => u.Department).ToList();
                    break;
                case "project_desc":
                    resQuery = query.Select(u => new WorkersModel { Id = u.Id, Name = u.FullName, Department = (u.Department != null) ? u.Department.Name : "", ProjectsCount = u.Projects.Count, UserStatus = u.UserStatus }).Where(u => u.Name.Contains(q)).OrderByDescending(u => u.ProjectsCount).ToList();
                    break;
                case "status_desc":

PTM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/vue.js" type="text/javascript"></script>
    <script src="~/Scripts/vue-router.js" type="text/javascript"></script>

</head>
<body>


    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PTM", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>   

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Departments<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Departments", "Index", "Department")</li>
                            <li>@Html.ActionLink("Statistics", "Department", "Statistics")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("New Department", "Create", "Department")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Projects<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Projects", "Index", "Project")</li>
                            <li>@Html.ActionLink("Statistics", "Project", "Statistics")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("New Project", "Create", "Project")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Workers<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Workers", "Index", "Worker")</li>
                            <li>@Html.ActionLink("Statistics", "Worker", "Statistics")</li>
                            @*<li class="divider"></li>
                            <li>@Html.ActionLink("New Worker", "Create", "Worker")</li>*@
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Manager<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Invite", "Invite", "Account")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Chat<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Chat", "Index", "Chat")</li>                           
                        </ul>
                    </li>

                    @*<li>@Html.ActionLink("Departments", "Index", "Department")</li>*@ 
                    @*<li>@Html.ActionLink("Projects", "Index", "Project")</li>*@ 
                    @*<li>@Html.ActionLink("Workers", "Index", "Worker")</li>*@ 
                    @*<li>@Html.ActionLink("Invite", "Invite", "Account")</li>*@ 
                    @*<li>@Html.ActionLink("Chat", "Chat", "Home")</li>*@
                </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @Html.Partial("~/Views/Shared/_LoginPartial.cshtml")
                    </ul>
            </div>
            
        </div>
    </div>


    <div class="container body-content">
        @RenderBody()

    </div>



    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>